export const LANDING = '/';
export const HOME = '/home';
export const SIGN_UP = '/signup';
export const LOGIN = '/login';
export const PASSWORD_FORGET = '/pw-forget';
export const WRITE = '/write';
// export const POST = '/post/:user/:title';
// export const USER_POST = '/post/:user'
export const ACCOUNT = '/account';
export const ADMIN = '/admin';
